name: CI/CD Workflow

on:
  pull_request:
    branches:
      - '*'
      - '**'
  push:
    branches:
      - '*'
      - '**'
  release:
    types: [published]

jobs:
  check:
    uses: ./.github/workflows/check.yml
    with:
      platform: ubuntu-22.04

  build-linux:
    uses: ./.github/workflows/build.yml
    needs: check
    with:
      run_platform: ${{ matrix.platform }}
      image_name: ${{ matrix.image }}
      tool_chain: ${{ matrix.tool_chain }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-22.04
            tool_chain: gcc-11
            image: ros:humble-ros-core-jammy
          - platform: ubuntu-22.04-arm
            tool_chain: gcc-11
            image: ros:humble-ros-core-jammy
